# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cut_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cut(object):
    def setupUi(self, cut):
        cut.setObjectName("cut")
        cut.resize(584, 182)
        self.layoutWidget = QtWidgets.QWidget(cut)
        self.layoutWidget.setGeometry(QtCore.QRect(180, 130, 195, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.okButton = QtWidgets.QPushButton(self.layoutWidget)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_6.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_6.addWidget(self.cancelButton)
        self.widget = QtWidgets.QWidget(cut)
        self.widget.setGeometry(QtCore.QRect(15, 16, 551, 101))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_openpath = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_openpath.setPlaceholderText("")
        self.lineEdit_openpath.setObjectName("lineEdit_openpath")
        self.gridLayout.addWidget(self.lineEdit_openpath, 0, 1, 1, 2)
        self.openButton = QtWidgets.QPushButton(self.widget)
        self.openButton.setObjectName("openButton")
        self.gridLayout.addWidget(self.openButton, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit_w = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_w.setObjectName("lineEdit_w")
        self.gridLayout.addWidget(self.lineEdit_w, 1, 1, 1, 1)
        self.lineEdit_h = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_h.setObjectName("lineEdit_h")
        self.gridLayout.addWidget(self.lineEdit_h, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_savepath = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_savepath.setObjectName("lineEdit_savepath")
        self.gridLayout.addWidget(self.lineEdit_savepath, 2, 1, 1, 2)
        self.saveButton = QtWidgets.QPushButton(self.widget)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 2, 3, 1, 1)

        self.retranslateUi(cut)
        QtCore.QMetaObject.connectSlotsByName(cut)

    def retranslateUi(self, cut):
        _translate = QtCore.QCoreApplication.translate
        cut.setWindowTitle(_translate("cut", "分割栅格"))
        self.okButton.setText(_translate("cut", "确定"))
        self.cancelButton.setText(_translate("cut", "取消"))
        self.label_2.setText(_translate("cut", "输入栅格"))
        self.openButton.setText(_translate("cut", "浏览"))
        self.label.setText(_translate("cut", "分割大小"))
        self.lineEdit_w.setPlaceholderText(_translate("cut", "宽"))
        self.lineEdit_h.setPlaceholderText(_translate("cut", "高"))
        self.label_3.setText(_translate("cut", "输出文件夹"))
        self.saveButton.setText(_translate("cut", "浏览"))
