# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datasetaug_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataSetAug(object):
    def setupUi(self, DataSetAug):
        DataSetAug.setObjectName("DataSetAug")
        DataSetAug.resize(607, 208)
        self.widget = QtWidgets.QWidget(DataSetAug)
        self.widget.setGeometry(QtCore.QRect(20, 30, 571, 111))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditinputDataset = QtWidgets.QLineEdit(self.widget)
        self.lineEditinputDataset.setObjectName("lineEditinputDataset")
        self.gridLayout.addWidget(self.lineEditinputDataset, 0, 1, 1, 3)
        self.pushButtonInput = QtWidgets.QPushButton(self.widget)
        self.pushButtonInput.setObjectName("pushButtonInput")
        self.gridLayout.addWidget(self.pushButtonInput, 0, 4, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 1, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 1, 2, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditOutputDir = QtWidgets.QLineEdit(self.widget)
        self.lineEditOutputDir.setObjectName("lineEditOutputDir")
        self.gridLayout.addWidget(self.lineEditOutputDir, 2, 1, 1, 3)
        self.pushButton_outputDir = QtWidgets.QPushButton(self.widget)
        self.pushButton_outputDir.setObjectName("pushButton_outputDir")
        self.gridLayout.addWidget(self.pushButton_outputDir, 2, 4, 1, 1)
        self.widget1 = QtWidgets.QWidget(DataSetAug)
        self.widget1.setGeometry(QtCore.QRect(170, 160, 231, 30))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonOK = QtWidgets.QPushButton(self.widget1)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout.addWidget(self.pushButtonOK)
        self.pushButtonCancel = QtWidgets.QPushButton(self.widget1)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)

        self.retranslateUi(DataSetAug)
        QtCore.QMetaObject.connectSlotsByName(DataSetAug)

    def retranslateUi(self, DataSetAug):
        _translate = QtCore.QCoreApplication.translate
        DataSetAug.setWindowTitle(_translate("DataSetAug", "Dialog"))
        self.label.setText(_translate("DataSetAug", "选择数据集"))
        self.pushButtonInput.setText(_translate("DataSetAug", "浏览"))
        self.checkBox.setText(_translate("DataSetAug", "水平翻转"))
        self.checkBox_2.setText(_translate("DataSetAug", "垂直翻转"))
        self.checkBox_3.setText(_translate("DataSetAug", "旋转"))
        self.label_3.setText(_translate("DataSetAug", "保存数据集"))
        self.pushButton_outputDir.setText(_translate("DataSetAug", "浏览"))
        self.pushButtonOK.setText(_translate("DataSetAug", "确定"))
        self.pushButtonCancel.setText(_translate("DataSetAug", "取消"))
