# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datasetdivide.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DatasstDvide(object):
    def setupUi(self, DatasstDvide):
        DatasstDvide.setObjectName("DatasstDvide")
        DatasstDvide.resize(602, 263)
        self.widget = QtWidgets.QWidget(DatasstDvide)
        self.widget.setGeometry(QtCore.QRect(10, 50, 571, 121))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_inputDIR = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_inputDIR.setObjectName("lineEdit_inputDIR")
        self.gridLayout.addWidget(self.lineEdit_inputDIR, 0, 1, 1, 2)
        self.pushButton_input = QtWidgets.QPushButton(self.widget)
        self.pushButton_input.setObjectName("pushButton_input")
        self.gridLayout.addWidget(self.pushButton_input, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_train = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_train.setObjectName("lineEdit_train")
        self.gridLayout.addWidget(self.lineEdit_train, 1, 1, 1, 1)
        self.lineEdit_test = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_test.setObjectName("lineEdit_test")
        self.gridLayout.addWidget(self.lineEdit_test, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_save = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_save.setObjectName("lineEdit_save")
        self.gridLayout.addWidget(self.lineEdit_save, 2, 1, 1, 2)
        self.pushButton_save = QtWidgets.QPushButton(self.widget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 2, 3, 1, 1)
        self.widget1 = QtWidgets.QWidget(DatasstDvide)
        self.widget1.setGeometry(QtCore.QRect(180, 190, 241, 41))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ok = QtWidgets.QPushButton(self.widget1)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget1)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)

        self.retranslateUi(DatasstDvide)
        QtCore.QMetaObject.connectSlotsByName(DatasstDvide)

    def retranslateUi(self, DatasstDvide):
        _translate = QtCore.QCoreApplication.translate
        DatasstDvide.setWindowTitle(_translate("DatasstDvide", "Dialog"))
        self.label.setText(_translate("DatasstDvide", "选择数据集"))
        self.pushButton_input.setText(_translate("DatasstDvide", "浏览"))
        self.label_3.setText(_translate("DatasstDvide", "训练集-测试集比例"))
        self.lineEdit_train.setPlaceholderText(_translate("DatasstDvide", "8"))
        self.lineEdit_test.setPlaceholderText(_translate("DatasstDvide", "1"))
        self.label_2.setText(_translate("DatasstDvide", "保存路径"))
        self.pushButton_save.setText(_translate("DatasstDvide", "浏览"))
        self.pushButton_ok.setText(_translate("DatasstDvide", "确定"))
        self.pushButton_cancel.setText(_translate("DatasstDvide", "取消"))
