# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogClassify.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogClassify(object):
    def setupUi(self, DialogClassify):
        DialogClassify.setObjectName("DialogClassify")
        DialogClassify.resize(746, 275)
        self.layoutWidget = QtWidgets.QWidget(DialogClassify)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 50, 591, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_outputDir = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_outputDir.setObjectName("lineEdit_outputDir")
        self.gridLayout.addWidget(self.lineEdit_outputDir, 1, 1, 1, 2)
        self.pushButton_outputDir = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_outputDir.setObjectName("pushButton_outputDir")
        self.gridLayout.addWidget(self.pushButton_outputDir, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.pushButton_inputImg = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_inputImg.setObjectName("pushButton_inputImg")
        self.gridLayout.addWidget(self.pushButton_inputImg, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_inputImg = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_inputImg.setObjectName("lineEdit_inputImg")
        self.gridLayout.addWidget(self.lineEdit_inputImg, 0, 1, 1, 2)
        self.pushButtonOK = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.gridLayout.addWidget(self.pushButtonOK, 2, 1, 1, 1)
        self.pushButtonCancel = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout.addWidget(self.pushButtonCancel, 2, 2, 1, 1)

        self.retranslateUi(DialogClassify)
        QtCore.QMetaObject.connectSlotsByName(DialogClassify)

    def retranslateUi(self, DialogClassify):
        _translate = QtCore.QCoreApplication.translate
        DialogClassify.setWindowTitle(_translate("DialogClassify", "地物分类"))
        self.pushButton_outputDir.setText(_translate("DialogClassify", "浏览"))
        self.label_3.setText(_translate("DialogClassify", "输出文件夹"))
        self.pushButton_inputImg.setText(_translate("DialogClassify", "浏览"))
        self.label.setText(_translate("DialogClassify", "输入影像"))
        self.pushButtonOK.setText(_translate("DialogClassify", "确定"))
        self.pushButtonCancel.setText(_translate("DialogClassify", "取消"))
