# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proj_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjDef(object):
    def setupUi(self, ProjDef):
        ProjDef.setObjectName("ProjDef")
        ProjDef.resize(576, 240)
        self.layoutWidget = QtWidgets.QWidget(ProjDef)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 40, 511, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton_NOXY = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_NOXY.setObjectName("pushButton_NOXY")
        self.gridLayout.addWidget(self.pushButton_NOXY, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_HaveXY = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_HaveXY.setObjectName("pushButton_HaveXY")
        self.gridLayout.addWidget(self.pushButton_HaveXY, 1, 2, 1, 1)
        self.lineEdit_no = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_no.setObjectName("lineEdit_no")
        self.gridLayout.addWidget(self.lineEdit_no, 0, 1, 1, 1)
        self.lineEdit_have = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_have.setObjectName("lineEdit_have")
        self.gridLayout.addWidget(self.lineEdit_have, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(ProjDef)
        self.layoutWidget1.setGeometry(QtCore.QRect(160, 170, 251, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ok = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)

        self.retranslateUi(ProjDef)
        QtCore.QMetaObject.connectSlotsByName(ProjDef)

    def retranslateUi(self, ProjDef):
        _translate = QtCore.QCoreApplication.translate
        ProjDef.setWindowTitle(_translate("ProjDef", "定义投影"))
        self.label_2.setText(_translate("ProjDef", "有空间参考影像"))
        self.pushButton_NOXY.setText(_translate("ProjDef", "浏览"))
        self.label.setText(_translate("ProjDef", "无空间参考影像"))
        self.pushButton_HaveXY.setText(_translate("ProjDef", "浏览"))
        self.pushButton_ok.setText(_translate("ProjDef", "确定"))
        self.pushButton_cancel.setText(_translate("ProjDef", "取消"))
