# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'R2V_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Raster2Vector(object):
    def setupUi(self, Raster2Vector):
        Raster2Vector.setObjectName("Raster2Vector")
        Raster2Vector.resize(746, 257)
        self.layoutWidget = QtWidgets.QWidget(Raster2Vector)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 40, 591, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_raster = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_raster.setObjectName("lineEdit_raster")
        self.gridLayout.addWidget(self.lineEdit_raster, 0, 1, 1, 2)
        self.pushButton_raster = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_raster.setObjectName("pushButton_raster")
        self.gridLayout.addWidget(self.pushButton_raster, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_outputDir = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_outputDir.setObjectName("lineEdit_outputDir")
        self.gridLayout.addWidget(self.lineEdit_outputDir, 1, 1, 1, 2)
        self.pushButton_outputDir = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_outputDir.setObjectName("pushButton_outputDir")
        self.gridLayout.addWidget(self.pushButton_outputDir, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_outputName = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_outputName.setObjectName("lineEdit_outputName")
        self.gridLayout.addWidget(self.lineEdit_outputName, 2, 1, 1, 2)
        self.pushButton_ok = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.gridLayout.addWidget(self.pushButton_ok, 3, 1, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 3, 2, 1, 1)

        self.retranslateUi(Raster2Vector)
        QtCore.QMetaObject.connectSlotsByName(Raster2Vector)

    def retranslateUi(self, Raster2Vector):
        _translate = QtCore.QCoreApplication.translate
        Raster2Vector.setWindowTitle(_translate("Raster2Vector", "栅格转矢量"))
        self.label.setText(_translate("Raster2Vector", "栅格数据"))
        self.pushButton_raster.setText(_translate("Raster2Vector", "浏览"))
        self.label_2.setText(_translate("Raster2Vector", "输出文件夹"))
        self.pushButton_outputDir.setText(_translate("Raster2Vector", "浏览"))
        self.label_3.setText(_translate("Raster2Vector", "保存文件名"))
        self.pushButton_ok.setText(_translate("Raster2Vector", "确定"))
        self.pushButton_cancel.setText(_translate("Raster2Vector", "取消"))
