# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stretch_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImgStretch(object):
    def setupUi(self, ImgStretch):
        ImgStretch.setObjectName("ImgStretch")
        ImgStretch.resize(646, 184)
        self.widget = QtWidgets.QWidget(ImgStretch)
        self.widget.setGeometry(QtCore.QRect(41, 32, 551, 131))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)

        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_input = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.gridLayout.addWidget(self.lineEdit_input, 0, 1, 1, 1)
        self.input_Button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_Button.setFont(font)
        self.input_Button.setObjectName("input_Button")
        self.gridLayout.addWidget(self.input_Button, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_savedir = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_savedir.setObjectName("lineEdit_savedir")
        self.gridLayout.addWidget(self.lineEdit_savedir, 1, 1, 1, 1)
        self.output_Button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_Button.setFont(font)
        self.output_Button.setObjectName("output_Button")
        self.gridLayout.addWidget(self.output_Button, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_saveName = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_saveName.setObjectName("lineEdit_saveName")
        self.gridLayout.addWidget(self.lineEdit_saveName, 2, 1, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ensure_pushButton = QtWidgets.QPushButton(self.widget)
        self.ensure_pushButton.setObjectName("ensure_pushButton")
        self.horizontalLayout.addWidget(self.ensure_pushButton)
        self.cancel_pushButton = QtWidgets.QPushButton(self.widget)
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.horizontalLayout.addWidget(self.cancel_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)

        self.retranslateUi(ImgStretch)
        QtCore.QMetaObject.connectSlotsByName(ImgStretch)

    def retranslateUi(self, ImgStretch):
        _translate = QtCore.QCoreApplication.translate
        ImgStretch.setWindowTitle(_translate("ImgStretch", "百分比截断拉伸"))
        self.label.setText(_translate("ImgStretch", "输入栅格"))
        self.input_Button.setText(_translate("ImgStretch", "浏览"))
        self.label_3.setText(_translate("ImgStretch", "输出文件夹"))
        self.output_Button.setText(_translate("ImgStretch", "浏览"))
        self.label_2.setText(_translate("ImgStretch", "输出文件名"))
        self.ensure_pushButton.setText(_translate("ImgStretch", "确定"))
        self.cancel_pushButton.setText(_translate("ImgStretch", "取消"))
