# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v2r_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Vector2Raster(object):
    def setupUi(self, Vector2Raster):
        Vector2Raster.setObjectName("Vector2Raster")
        Vector2Raster.resize(666, 206)
        self.widget = QtWidgets.QWidget(Vector2Raster)
        self.widget.setGeometry(QtCore.QRect(50, 20, 531, 151))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_vector = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_vector.setObjectName("lineEdit_vector")
        self.gridLayout.addWidget(self.lineEdit_vector, 0, 1, 1, 2)
        self.pushButton_vector = QtWidgets.QPushButton(self.widget)
        self.pushButton_vector.setObjectName("pushButton_vector")
        self.gridLayout.addWidget(self.pushButton_vector, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_tempfile = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_tempfile.setObjectName("lineEdit_tempfile")
        self.gridLayout.addWidget(self.lineEdit_tempfile, 1, 1, 1, 2)
        self.pushButton_tempfile = QtWidgets.QPushButton(self.widget)
        self.pushButton_tempfile.setObjectName("pushButton_tempfile")
        self.gridLayout.addWidget(self.pushButton_tempfile, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_outdir = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_outdir.setObjectName("lineEdit_outdir")
        self.gridLayout.addWidget(self.lineEdit_outdir, 2, 1, 1, 2)
        self.pushButton_raster = QtWidgets.QPushButton(self.widget)
        self.pushButton_raster.setObjectName("pushButton_raster")
        self.gridLayout.addWidget(self.pushButton_raster, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit_outname = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_outname.setObjectName("lineEdit_outname")
        self.gridLayout.addWidget(self.lineEdit_outname, 3, 1, 1, 2)
        self.pushButton_ok = QtWidgets.QPushButton(self.widget)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.gridLayout.addWidget(self.pushButton_ok, 4, 1, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 4, 2, 1, 1)

        self.retranslateUi(Vector2Raster)
        QtCore.QMetaObject.connectSlotsByName(Vector2Raster)

    def retranslateUi(self, Vector2Raster):
        _translate = QtCore.QCoreApplication.translate
        Vector2Raster.setWindowTitle(_translate("Vector2Raster", "矢量转栅格"))
        self.label.setText(_translate("Vector2Raster", "矢量数据："))
        self.pushButton_vector.setText(_translate("Vector2Raster", "浏览"))
        self.label_4.setText(_translate("Vector2Raster", "参考文件"))
        self.pushButton_tempfile.setText(_translate("Vector2Raster", "浏览"))
        self.label_2.setText(_translate("Vector2Raster", "输出文件夹"))
        self.pushButton_raster.setText(_translate("Vector2Raster", "浏览"))
        self.label_3.setText(_translate("Vector2Raster", "保存文件名"))
        self.pushButton_ok.setText(_translate("Vector2Raster", "确定"))
        self.pushButton_cancel.setText(_translate("Vector2Raster", "取消"))
