# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yolotrans_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YOLOTRANS(object):
    def setupUi(self, YOLOTRANS):
        YOLOTRANS.setObjectName("YOLOTRANS")
        YOLOTRANS.resize(574, 260)
        self.widget = QtWidgets.QWidget(YOLOTRANS)
        self.widget.setGeometry(QtCore.QRect(60, 40, 481, 121))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditinDIR = QtWidgets.QLineEdit(self.widget)
        self.lineEditinDIR.setObjectName("lineEditinDIR")
        self.gridLayout.addWidget(self.lineEditinDIR, 0, 1, 1, 1)
        self.pushButtoninput = QtWidgets.QPushButton(self.widget)
        self.pushButtoninput.setObjectName("pushButtoninput")
        self.gridLayout.addWidget(self.pushButtoninput, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_outDir = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_outDir.setObjectName("lineEdit_outDir")
        self.gridLayout.addWidget(self.lineEdit_outDir, 1, 1, 1, 1)
        self.pushButton_outDir = QtWidgets.QPushButton(self.widget)
        self.pushButton_outDir.setObjectName("pushButton_outDir")
        self.gridLayout.addWidget(self.pushButton_outDir, 1, 2, 1, 1)
        self.widget1 = QtWidgets.QWidget(YOLOTRANS)
        self.widget1.setGeometry(QtCore.QRect(150, 190, 261, 41))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ok = QtWidgets.QPushButton(self.widget1)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget1)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)

        self.retranslateUi(YOLOTRANS)
        QtCore.QMetaObject.connectSlotsByName(YOLOTRANS)

    def retranslateUi(self, YOLOTRANS):
        _translate = QtCore.QCoreApplication.translate
        YOLOTRANS.setWindowTitle(_translate("YOLOTRANS", "VOC2YOLO"))
        self.label.setText(_translate("YOLOTRANS", "VOC数据集"))
        self.pushButtoninput.setText(_translate("YOLOTRANS", "浏览"))
        self.label_2.setText(_translate("YOLOTRANS", "保存路径"))
        self.pushButton_outDir.setText(_translate("YOLOTRANS", "浏览"))
        self.pushButton_ok.setText(_translate("YOLOTRANS", "确定"))
        self.pushButton_cancel.setText(_translate("YOLOTRANS", "取消"))
